
export const ADDITIONAL_RECIPES = [
  {
    id: "101",
    title: "Creamy Butter Chicken",
    description: "A classic Indian dish with tender chicken in a rich, creamy tomato sauce.",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db",
    time: "45 mins",
    servings: 4,
    category: "Indian",
    difficulty: "Medium",
    ingredients: [
      "1 kg chicken thighs, boneless and skinless",
      "2 tbsp butter",
      "1 large onion, finely chopped",
      "4 cloves garlic, minced",
      "2 tbsp ginger, grated",
      "2 tbsp garam masala",
      "2 tsp turmeric",
      "2 tsp cumin",
      "1 cup tomato puree",
      "1 cup heavy cream",
      "Fresh coriander for garnish"
    ],
    instructions: "1. Marinate chicken in yogurt, turmeric, and salt for 2 hours.\n2. Melt butter in a pan and sauté onions until golden.\n3. Add garlic, ginger, and spices, cook for 2 minutes.\n4. Add tomato puree and simmer for 10 minutes.\n5. Add chicken and cook for 15 minutes.\n6. Stir in cream and simmer for 10 minutes.\n7. Garnish with fresh coriander."
  },
  {
    id: "102",
    title: "Authentic Lamb Biryani",
    description: "Fragrant basmati rice layered with spiced lamb, fresh herbs, and caramelized onions.",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8",
    time: "90 mins",
    servings: 6,
    category: "Indian",
    difficulty: "Hard",
    ingredients: [
      "1 kg lamb, cut into pieces",
      "3 cups basmati rice, soaked for 30 minutes",
      "4 large onions, thinly sliced",
      "6 cloves garlic, minced",
      "2 tbsp ginger, grated",
      "3 tomatoes, chopped",
      "1/4 cup mint leaves",
      "1/4 cup coriander leaves",
      "3 green chilies, sliced",
      "1 tbsp biryani masala",
      "1 tsp turmeric powder",
      "2 cinnamon sticks",
      "4 cardamom pods",
      "4 cloves",
      "Saffron strands soaked in warm milk"
    ],
    instructions: "1. Marinate lamb with yogurt and spices for 4 hours.\n2. Fry onions until caramelized and set aside.\n3. Cook lamb with tomatoes and spices until tender.\n4. Parboil rice with whole spices until 70% cooked.\n5. Layer rice and lamb in a heavy-bottomed pot.\n6. Sprinkle with herbs, fried onions, and saffron milk.\n7. Cover tightly and cook on low heat for 25 minutes.\n8. Let it rest for 10 minutes before serving."
  },
  {
    id: "103",
    title: "Homemade Naan Bread",
    description: "Soft and fluffy Indian flatbread that's perfect for scooping up curries.",
    image: "https://images.unsplash.com/photo-1584906093595-6b488e7f3c8e",
    time: "30 mins",
    servings: 8,
    category: "Indian",
    difficulty: "Easy",
    ingredients: [
      "4 cups all-purpose flour",
      "1 tsp baking powder",
      "1 tsp baking soda",
      "1 tsp sugar",
      "1 tsp salt",
      "1 egg, beaten",
      "3/4 cup warm milk",
      "1/4 cup yogurt",
      "2 tbsp vegetable oil",
      "2 tbsp melted butter for brushing",
      "1 tbsp nigella seeds (optional)"
    ],
    instructions: "1. Mix dry ingredients in a large bowl.\n2. Add egg, warm milk, yogurt, and oil to form a soft dough.\n3. Knead for 5 minutes, then cover and rest for 2 hours.\n4. Divide into 8 balls and roll into tear-drop shapes.\n5. Heat a cast iron skillet until very hot.\n6. Cook naan for 1-2 minutes each side until bubbles form and brown.\n7. Brush with melted butter and sprinkle with nigella seeds."
  },
  {
    id: "104",
    title: "Perfect Vegetable Curry",
    description: "A hearty vegetable curry with a rich, spiced tomato sauce that's both healthy and flavorful.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd",
    time: "40 mins",
    servings: 4,
    category: "Vegetarian",
    difficulty: "Medium",
    ingredients: [
      "2 potatoes, diced",
      "1 cauliflower, cut into florets",
      "2 carrots, sliced",
      "1 cup green peas",
      "1 onion, finely chopped",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 tomatoes, pureed",
      "1 tbsp curry powder",
      "1 tsp turmeric",
      "1 tsp cumin",
      "1 tsp coriander powder",
      "1/2 tsp red chili powder",
      "1 cup coconut milk",
      "Fresh coriander for garnish"
    ],
    instructions: "1. Heat oil in a large pot and sauté onions until translucent.\n2. Add garlic and ginger, cook for 1 minute.\n3. Add spices and cook for another minute.\n4. Add tomato puree and cook until oil separates.\n5. Add vegetables and cook for 5 minutes.\n6. Pour in 1 cup water, cover and simmer for 15 minutes.\n7. Add coconut milk and simmer for another 5 minutes.\n8. Garnish with fresh coriander."
  },
  {
    id: "105",
    title: "Decadent Chocolate Cake",
    description: "An irresistibly moist and rich chocolate cake that's perfect for any celebration.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
    time: "60 mins",
    servings: 12,
    category: "Desserts",
    difficulty: "Medium",
    ingredients: [
      "2 cups all-purpose flour",
      "2 cups sugar",
      "3/4 cup unsweetened cocoa powder",
      "2 tsp baking soda",
      "1 tsp baking powder",
      "1 tsp salt",
      "2 eggs",
      "1 cup buttermilk",
      "1/2 cup vegetable oil",
      "2 tsp vanilla extract",
      "1 cup hot coffee",
      "For frosting: 1 cup butter, 3.5 cups powdered sugar, 3/4 cup cocoa, 1/3 cup milk"
    ],
    instructions: "1. Preheat oven to 350°F (175°C) and grease two 9-inch round cake pans.\n2. Combine dry ingredients in a large bowl.\n3. Add eggs, buttermilk, oil, and vanilla. Beat for 2 minutes.\n4. Stir in hot coffee (batter will be thin).\n5. Pour into prepared pans and bake for 30-35 minutes.\n6. For frosting, beat butter until creamy, then add powdered sugar, cocoa, and milk.\n7. Frost cooled cake layers and enjoy!"
  },
  {
    id: "106",
    title: "Homemade Pizza Dough",
    description: "A foolproof pizza dough recipe that creates the perfect balance of crispy and chewy crust.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002",
    time: "2 hours",
    servings: 4,
    category: "Italian",
    difficulty: "Medium",
    ingredients: [
      "3.5 cups all-purpose flour",
      "1 tsp sugar",
      "2.25 tsp active dry yeast",
      "2 tsp salt",
      "1.5 cups warm water",
      "2 tbsp olive oil, plus more for bowl"
    ],
    instructions: "1. Combine warm water, sugar, and yeast in a bowl. Let sit for 5 minutes until foamy.\n2. In a large bowl, mix flour and salt.\n3. Add the yeast mixture and olive oil to the flour.\n4. Mix until a dough forms, then knead for 5-7 minutes until smooth.\n5. Place in an oiled bowl, cover, and let rise for 1 hour.\n6. Punch down dough and divide into 2 balls.\n7. Let rest for 15 minutes, then shape, top, and bake at 475°F for 10-12 minutes."
  }
];
