export const MOCK_RECIPES = [
  {
    id: 1,
    title: "Classic Margherita Pizza",
    description: "A traditional Italian pizza with fresh basil, mozzarella, and tomatoes. This authentic recipe brings the taste of Naples to your home kitchen.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "30 min",
    servings: 4,
    category: "Italian",
    ingredients: [
      "2 cups all-purpose flour",
      "1 cup warm water",
      "2 1/4 tsp active dry yeast",
      "Fresh mozzarella",
      "Fresh basil leaves",
      "San Marzano tomatoes",
      "Extra virgin olive oil",
      "Salt to taste"
    ],
    instructions: [
      "Prepare the pizza dough by mixing flour, yeast, and warm water",
      "Let the dough rise for 1-2 hours",
      "Stretch the dough into a circle",
      "Add tomato sauce, fresh mozzarella, and basil",
      "Bake at 450°F for 12-15 minutes"
    ]
  },
  {
    id: 2,
    title: "Chocolate Chip Cookies",
    description: "Soft and chewy cookies loaded with chocolate chips",
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "25 min",
    servings: 24,
    category: "Desserts",
  },
  {
    id: 3,
    title: "Greek Salad",
    description: "Fresh Mediterranean salad with feta cheese and olives",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "15 min",
    servings: 2,
    category: "Salads",
  },
  {
    id: 4,
    title: "Beef Stir Fry",
    description: "Quick and easy Asian-style beef with vegetables",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "20 min",
    servings: 4,
    category: "Asian",
  },
  {
    id: 5,
    title: "Banana Bread",
    description: "Moist and delicious homemade banana bread",
    image: "https://images.unsplash.com/photo-1584736286279-4a5f6e2b0858?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "1 hour",
    servings: 8,
    category: "Baking",
  },
  {
    id: 6,
    title: "Vegetable Curry",
    description: "Aromatic Indian curry with mixed vegetables",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "45 min",
    servings: 6,
    category: "Indian",
  },
  {
    id: 7,
    title: "Butter Chicken",
    description: "Creamy and rich Indian curry with tender chicken pieces in a tomato-based sauce",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "45 min",
    servings: 4,
    category: "Indian",
  },
  {
    id: 8,
    title: "Palak Paneer",
    description: "Cottage cheese cubes in a creamy spinach gravy",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "40 min",
    servings: 4,
    category: "Indian",
  },
  {
    id: 9,
    title: "Biryani",
    description: "Aromatic rice dish with spices and tender meat",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "1 hour",
    servings: 6,
    category: "Indian",
  },
  {
    id: 10,
    title: "Dal Makhani",
    description: "Creamy black lentils simmered overnight",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "45 min",
    servings: 4,
    category: "Indian",
  },
  {
    id: 11,
    title: "Chole Bhature",
    description: "Spiced chickpeas served with fried bread",
    image: "https://images.unsplash.com/photo-1626132647957-5659d0bc9222?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "50 min",
    servings: 4,
    category: "Indian",
  },
  {
    id: 50,
    title: "Masala Dosa",
    description: "Crispy rice crepe filled with spiced potatoes",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "30 min",
    servings: 2,
    category: "Indian",
  }
];
