<lov-code>
export const MOCK_RECIPES = [
  {
    id: 1,
    title: "Classic Margherita Pizza",
    description: "A traditional Italian pizza with fresh basil, mozzarella, and tomatoes. This authentic recipe brings the taste of Naples to your home kitchen.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "30 min",
    servings: 4,
    category: "Italian",
    ingredients: [
      "2 cups all-purpose flour",
      "1 cup warm water",
      "2 1/4 tsp active dry yeast",
      "Fresh mozzarella",
      "Fresh basil leaves",
      "San Marzano tomatoes",
      "Extra virgin olive oil",
      "Salt to taste"
    ],
    instructions: [
      "Prepare the pizza dough by mixing flour, yeast, and warm water",
      "Let the dough rise for 1-2 hours",
      "Stretch the dough into a circle",
      "Add tomato sauce, fresh mozzarella, and basil",
      "Bake at 450°F for 12-15 minutes"
    ]
  },
  {
    id: 2,
    title: "Chocolate Chip Cookies",
    description: "Soft and chewy cookies loaded with chocolate chips. Perfect for dessert, snack time, or special occasions.",
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "25 min",
    servings: 24,
    category: "Desserts",
    ingredients: [
      "2 1/4 cups all-purpose flour",
      "1 cup butter, softened",
      "3/4 cup white sugar",
      "3/4 cup packed brown sugar",
      "2 large eggs",
      "2 tsp vanilla extract",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "2 cups chocolate chips"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C)",
      "Cream together butter and sugars until smooth",
      "Beat in eggs one at a time, then add vanilla",
      "Combine flour, baking soda, and salt; gradually add to the wet mixture",
      "Fold in chocolate chips",
      "Drop by rounded tablespoons onto ungreased baking sheets",
      "Bake for 9 to 11 minutes or until golden brown"
    ]
  },
  {
    id: 3,
    title: "Greek Salad",
    description: "Fresh Mediterranean salad with feta cheese and olives. A healthy and refreshing side dish or light meal.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "15 min",
    servings: 2,
    category: "Salads",
    ingredients: [
      "1 large cucumber, diced",
      "2 large tomatoes, diced",
      "1 red onion, thinly sliced",
      "1 bell pepper, diced",
      "1/2 cup kalamata olives",
      "200g feta cheese, cubed",
      "2 tbsp extra virgin olive oil",
      "1 tbsp red wine vinegar",
      "1 tsp dried oregano",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Combine cucumber, tomatoes, onion, bell pepper, and olives in a large bowl",
      "Add feta cheese cubes on top",
      "In a small bowl, whisk together olive oil, vinegar, oregano, salt, and pepper",
      "Drizzle dressing over the salad and toss gently",
      "Serve immediately or refrigerate for 30 minutes to enhance flavors"
    ]
  },
  {
    id: 4,
    title: "Beef Stir Fry",
    description: "Quick and easy Asian-style beef with vegetables. A flavorful dinner ready in minutes.",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "20 min",
    servings: 4,
    category: "Asian",
    ingredients: [
      "500g beef sirloin, thinly sliced",
      "2 tbsp vegetable oil",
      "1 onion, sliced",
      "2 bell peppers, sliced",
      "2 carrots, julienned",
      "2 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "3 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "1 tbsp sesame oil",
      "2 green onions, sliced for garnish",
      "Sesame seeds for garnish"
    ],
    instructions: [
      "Heat oil in a wok or large frying pan over high heat",
      "Add beef and stir-fry for 2-3 minutes until browned",
      "Remove beef and set aside",
      "In the same pan, add onion, bell peppers, and carrots. Stir-fry for 3 minutes",
      "Add garlic and ginger, stir-fry for 1 minute until fragrant",
      "Return beef to the pan, add soy sauce and oyster sauce",
      "Stir-fry everything together for 2 minutes",
      "Drizzle with sesame oil, garnish with green onions and sesame seeds"
    ]
  },
  {
    id: 5,
    title: "Banana Bread",
    description: "Moist and delicious homemade banana bread. The perfect way to use overripe bananas.",
    image: "https://images.unsplash.com/photo-1584736286279-4a5f6e2b0858?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "1 hour",
    servings: 8,
    category: "Baking",
    ingredients: [
      "3 ripe bananas, mashed",
      "1/3 cup melted butter",
      "1 tsp baking soda",
      "Pinch of salt",
      "3/4 cup sugar",
      "1 large egg, beaten",
      "1 tsp vanilla extract",
      "1 1/2 cups all-purpose flour",
      "1/2 cup walnuts or chocolate chips (optional)"
    ],
    instructions: [
      "Preheat oven to 350°F (175°C) and grease a 4x8-inch loaf pan",
      "Mix mashed bananas with melted butter in a large bowl",
      "Mix in baking soda and salt",
      "Stir in sugar, beaten egg, and vanilla extract",
      "Mix in flour",
      "Fold in nuts or chocolate chips if using",
      "Pour batter into prepared loaf pan",
      "Bake for 50-60 minutes until a toothpick inserted comes out clean"
    ]
  },
  {
    id: 6,
    title: "Vegetable Curry",
    description: "Aromatic Indian curry with mixed vegetables. A hearty vegetarian dish full of flavor.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "45 min",
    servings: 6,
    category: "Indian",
    ingredients: [
      "2 tbsp vegetable oil",
      "1 large onion, diced",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 tbsp curry powder",
      "1 tsp turmeric",
      "1 tsp ground cumin",
      "1/2 tsp red chili powder",
      "2 potatoes, diced",
      "2 carrots, sliced",
      "1 bell pepper, diced",
      "1 cup cauliflower florets",
      "1 cup green peas",
      "1 can (400ml) coconut milk",
      "1 can (400g) diced tomatoes",
      "Fresh cilantro for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Heat oil in a large pot over medium heat",
      "Add onion and sauté until translucent",
      "Add garlic and ginger, cook for 1 minute until fragrant",
      "Add curry powder, turmeric, cumin, and chili powder. Stir for 30 seconds",
      "Add potatoes, carrots, bell pepper, and cauliflower. Stir to coat with spices",
      "Add diced tomatoes and coconut milk. Bring to a simmer",
      "Cover and cook for 20 minutes until vegetables are tender",
      "Add green peas and cook for another 5 minutes",
      "Season with salt to taste and garnish with fresh cilantro"
    ]
  },
  {
    id: 7,
    title: "Butter Chicken",
    description: "Creamy and rich Indian curry with tender chicken pieces in a tomato-based sauce. A restaurant-style dish made at home.",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "45 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "500g boneless chicken thighs, cut into bite-sized pieces",
      "2 tbsp plain yogurt",
      "1 tbsp lemon juice",
      "1 tsp turmeric",
      "2 tsp garam masala",
      "1 tsp cumin",
      "2 tbsp butter",
      "1 large onion, finely chopped",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "1 can (400g) tomato puree",
      "1 cup heavy cream",
      "1 tbsp kasuri methi (dried fenugreek leaves)",
      "Fresh cilantro for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Marinate chicken with yogurt, lemon juice, turmeric, 1 tsp garam masala, and salt for at least 30 minutes",
      "Heat butter in a large pan over medium heat",
      "Add onion and sauté until golden brown",
      "Add garlic and ginger, cook for 1 minute until fragrant",
      "Add marinated chicken and cook until no longer pink, about 5-7 minutes",
      "Add tomato puree and bring to a simmer. Cook for 10 minutes",
      "Stir in heavy cream and remaining garam masala",
      "Simmer for 10 more minutes until sauce thickens",
      "Crush kasuri methi between your palms and add to the curry",
      "Adjust salt to taste and garnish with fresh cilantro"
    ]
  },
  {
    id: 8,
    title: "Palak Paneer",
    description: "Cottage cheese cubes in a creamy spinach gravy. A nutritious and popular North Indian dish.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "40 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "250g paneer, cubed",
      "500g spinach, washed",
      "2 tbsp ghee or oil",
      "1 large onion, finely chopped",
      "2 tomatoes, chopped",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 green chilies, chopped",
      "1 tsp cumin seeds",
      "1/2 tsp turmeric",
      "1 tsp garam masala",
      "1/2 tsp red chili powder",
      "2 tbsp heavy cream",
      "Salt to taste"
    ],
    instructions: [
      "Blanch spinach in boiling water for 2-3 minutes, then transfer to ice water",
      "Drain and blend the spinach into a smooth puree",
      "Heat 1 tbsp ghee in a pan and lightly fry paneer cubes until golden. Set aside",
      "In the same pan, add remaining ghee and cumin seeds",
      "When seeds splutter, add onion and sauté until golden brown",
      "Add garlic, ginger, and green chilies. Cook for 1 minute",
      "Add tomatoes and cook until soft and oil separates",
      "Add turmeric, red chili powder, and salt. Mix well",
      "Add spinach puree and cook for 5 minutes",
      "Add paneer cubes and garam masala. Simmer for 5 minutes",
      "Stir in cream and cook for 2 more minutes",
      "Serve hot with roti or rice"
    ]
  },
  {
    id: 9,
    title: "Biryani",
    description: "Aromatic rice dish with spices and tender meat. A festive and flavorful one-pot meal.",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "1 hour",
    servings: 6,
    category: "Indian",
    ingredients: [
      "500g basmati rice, soaked for 30 minutes",
      "500g chicken or lamb, cut into pieces",
      "2 large onions, thinly sliced",
      "3 tomatoes, chopped",
      "1/4 cup plain yogurt",
      "4 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 green chilies, slit",
      "1/4 cup mint leaves, chopped",
      "1/4 cup cilantro, chopped",
      "2 bay leaves",
      "4 cardamom pods",
      "1 cinnamon stick",
      "4 cloves",
      "1 star anise",
      "1 tsp cumin seeds",
      "2 tbsp biryani masala",
      "1/2 tsp turmeric",
      "1 pinch saffron soaked in 2 tbsp warm milk",
      "3 tbsp ghee or oil",
      "Salt to taste"
    ],
    instructions: [
      "Marinate meat with yogurt, half of the garlic and ginger, 1 tbsp biryani masala, turmeric, and salt for at least 1 hour",
      "Heat ghee in a large pot, add whole spices (bay leaves, cardamom, cinnamon, cloves, star anise, cumin seeds)",
      "Add sliced onions and fry until golden brown",
      "Add remaining ginger and garlic, green chilies, and sauté for 1 minute",
      "Add marinated meat and cook until browned",
      "Add tomatoes and cook until soft",
      "Add remaining biryani masala, half of the mint and cilantro. Mix well",
      "In a separate pot, cook soaked rice with salt until 70% done. Drain",
      "Layer the partially cooked rice over the meat mixture",
      "Sprinkle saffron milk and remaining mint and cilantro",
      "Cover with tight-fitting lid and cook on low heat for 20 minutes",
      "Let it rest for 5 minutes before gently mixing and serving"
    ]
  },
  {
    id: 10,
    title: "Dal Makhani",
    description: "Creamy black lentils simmered overnight. A rich and hearty vegetarian dish from Punjab.",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "45 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "1 cup whole black lentils (urad dal), soaked overnight",
      "1/4 cup red kidney beans (rajma), soaked overnight",
      "2 tbsp butter",
      "1 tbsp oil",
      "1 large onion, finely chopped",
      "2 tomatoes, pureed",
      "1 tbsp ginger-garlic paste",
      "1 green chili, slit",
      "1 tsp cumin seeds",
      "1/2 tsp turmeric",
      "1 tsp red chili powder",
      "1 tsp garam masala",
      "1/4 cup cream",
      "2 tbsp dried fenugreek leaves (kasuri methi)",
      "Fresh cilantro for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Cook soaked lentils and kidney beans with salt and turmeric in a pressure cooker until soft",
      "Heat butter and oil in a pan, add cumin seeds and let them splutter",
      "Add onion and sauté until golden brown",
      "Add ginger-garlic paste and green chili. Cook for 1 minute",
      "Add tomato puree and cook until oil separates",
      "Add red chili powder and salt. Mix well",
      "Add cooked lentils and kidney beans with their liquid",
      "Simmer on low heat for 20-25 minutes, stirring occasionally",
      "Add garam masala and dried fenugreek leaves",
      "Add cream and simmer for 5 more minutes",
      "Garnish with fresh cilantro and serve hot with naan or rice"
    ]
  },
  {
    id: 11,
    title: "Chole Bhature",
    description: "Spiced chickpeas served with fried bread. A popular Punjabi breakfast or lunch dish.",
    image: "https://images.unsplash.com/photo-1626132647957-5659d0bc9222?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "50 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "For Chole:",
      "2 cups chickpeas, soaked overnight",
      "2 large onions, finely chopped",
      "2 tomatoes, pureed",
      "1 tbsp ginger-garlic paste",
      "2 green chilies, chopped",
      "2 bay leaves",
      "1 cinnamon stick",
      "2 tsp chole masala",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp turmeric",
      "1 tsp red chili powder",
      "1 tsp amchur (dried mango powder)",
      "1 tsp garam masala",
      "2 tbsp oil",
      "Fresh cilantro for garnish",
      "For Bhature:",
      "2 cups all-purpose flour",
      "1/4 cup semolina (sooji)",
      "2 tbsp plain yogurt",
      "1/2 tsp baking powder",
      "1/4 tsp baking soda",
      "1 tbsp oil plus more for frying",
      "Warm water as needed",
      "Salt to taste"
    ],
    instructions: [
      "For Chole:",
      "Pressure cook soaked chickpeas with salt until soft",
      "Heat oil in a pan, add bay leaves and cinnamon stick",
      "Add onions and sauté until golden brown",
      "Add ginger-garlic paste and green chilies. Cook for 1 minute",
      "Add tomato puree and cook until oil separates",
      "Add all spice powders and mix well",
      "Add cooked chickpeas with some cooking liquid",
      "Simmer for 15-20 minutes until gravy thickens",
      "Garnish with fresh cilantro",
      "For Bhature:",
      "Mix flour, semolina, yogurt, baking powder, baking soda, oil, and salt",
      "Knead into a soft dough using warm water as needed",
      "Cover and let it rest for 2-3 hours",
      "Divide dough into small balls and roll into oval shapes",
      "Deep fry in hot oil until puffed and golden brown on both sides",
      "Serve hot bhature with chole"
    ]
  },
  {
    id: 50,
    title: "Masala Dosa",
    description: "Crispy rice crepe filled with spiced potatoes. A South Indian breakfast favorite.",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "30 min",
    servings: 2,
    category: "Indian",
    ingredients: [
      "For Dosa batter:",
      "2 cups rice, soaked for 4-6 hours",
      "1/2 cup urad dal, soaked for 4-6 hours",
      "1/4 tsp fenugreek seeds, soaked with urad dal",
      "Salt to taste",
      "For Potato filling:",
      "4 medium potatoes, boiled and mashed",
      "1 large onion, finely chopped",
      "1 tsp mustard seeds",
      "1 tsp cumin seeds",
      "1/4 tsp asafoetida (hing)",
      "10-15 curry leaves",
      "2-3 green chilies, finely chopped",
      "1/2 tsp turmeric powder",
      "1 tbsp oil",
      "Fresh cilantro, chopped",
      "Salt to taste",
      "For serving:",
      "Coconut chutney",
      "Sambar"
    ],
    instructions: [
      "For Dosa batter:",
      "Grind soaked rice and urad dal separately into a smooth paste",
      "Mix both pastes together, add salt, and ferment overnight",
      "For Potato filling:",
      "Heat oil in a pan, add mustard seeds and let them splutter",
      "Add cumin seeds, asafoetida, curry leaves, and green chilies",
      "Add onions and sauté until translucent",
      "Add turmeric powder and salt",
      "Add mashed potatoes and mix well. Cook for 3-4 minutes",
      "Add chopped cilantro and mix",
      "To make Masala Dosa:",
      "Heat a non-stick griddle or tawa",
      "Pour a ladleful of batter and spread in a circular motion",
      "Drizzle oil around the edges and cook until golden and crisp",
      "Place a portion of potato filling in the center",
      "Fold the dosa over the filling and serve hot with coconut chutney and sambar"
    ]
  },
  {
    id: 12,
    title: "Paneer Tikka Masala",
    description: "Grilled paneer cubes in a rich and creamy tomato-based sauce. A vegetarian delight that's popular in Indian restaurants worldwide.",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "40 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "400g paneer, cut into cubes",
      "1 large onion, finely chopped",
      "2 tomatoes, pureed",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 green chilies, slit",
      "1 tbsp tandoori masala",
      "1 tsp garam masala",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp turmeric powder",
      "1 tsp kasuri methi (dried fenugreek leaves)",
      "200ml heavy cream",
      "2 tbsp vegetable oil",
      "2 tbsp butter",
      "Fresh cilantro for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Marinate paneer cubes in yogurt, tandoori masala, and salt for 30 minutes",
      "Grill or pan-fry the marinated paneer until golden and set aside",
      "Heat oil and butter in a pan, add cumin seeds and let them splutter",
      "Add onions and sauté until golden brown",
      "Add ginger, garlic, and green chilies, cook for 1-2 minutes",
      "Add tomato puree and cook until oil separates",
      "Add all the spice powders and mix well",
      "Add cream and simmer for 5 minutes",
      "Add the grilled paneer and kasuri methi, simmer for another 5 minutes",
      "Garnish with fresh cilantro and serve hot with naan or rice"
    ]
  },
  {
    id: 13,
    title: "Mushroom Risotto",
    description: "Creamy Italian rice dish with mushrooms and Parmesan cheese. A comforting vegetarian meal that's both elegant and satisfying.",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "35 min",
    servings: 4,
    category: "Italian",
    ingredients: [
      "1 1/2 cups Arborio rice",
      "300g mixed mushrooms (cremini, shiitake, oyster), sliced",
      "1 medium onion, finely diced",
      "2 cloves garlic, minced",
      "1/2 cup dry white wine",
      "4 cups vegetable broth, kept warm",
      "1/2 cup grated Parmesan cheese",
      "2 tbsp butter",
      "2 tbsp olive oil",
      "2 tbsp fresh thyme leaves",
      "1 tbsp fresh parsley, chopped",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Heat olive oil in a large pan, add mushrooms and cook until golden brown",
      "Remove mushrooms and set aside",
      "In the same pan, add butter, onion, and garlic. Sauté until translucent",
      "Add Arborio rice and toast for 2-3 minutes",
      "Pour in white wine and stir until absorbed",
      "Gradually add warm broth, one ladle at a time, stirring constantly",
      "Continue adding broth and stirring until rice is creamy and al dente (about 18-20 minutes)",
      "Stir in cooked mushrooms, Parmesan cheese, and thyme",
      "Season with salt and pepper, garnish with parsley",
      "Serve immediately for the best creamy texture"
    ]
  },
  {
    id: 14,
    title: "Vegetable Lasagna",
    description: "Layers of pasta, rich tomato sauce, and assorted vegetables topped with creamy béchamel and cheese. A hearty vegetarian twist on the Italian classic.",
    image: "https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "75 min",
    servings: 8,
    category: "Italian",
    ingredients: [
      "12 lasagna noodles",
      "2 zucchini, diced",
      "1 eggplant, diced",
      "1 red bell pepper, diced",
      "2 cups spinach, chopped",
      "1 large onion, diced",
      "3 cloves garlic, minced",
      "2 cans (400g each) crushed tomatoes",
      "2 tbsp tomato paste",
      "1 tsp dried oregano",
      "1 tsp dried basil",
      "1/4 tsp red pepper flakes",
      "2 cups ricotta cheese",
      "2 cups mozzarella cheese, shredded",
      "1 cup Parmesan cheese, grated",
      "1 egg, beaten",
      "3 tbsp olive oil",
      "Salt and pepper to taste",
      "Fresh basil for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C)",
      "Cook lasagna noodles according to package instructions",
      "In a large pan, heat olive oil and sauté onions and garlic until soft",
      "Add zucchini, eggplant, and bell pepper. Cook until tender",
      "Add crushed tomatoes, tomato paste, dried herbs, and seasonings",
      "Simmer sauce for 15-20 minutes until slightly thickened",
      "In a bowl, mix ricotta cheese, half the mozzarella, half the Parmesan, and the beaten egg",
      "In a 9x13 baking dish, spread a thin layer of tomato sauce",
      "Layer with lasagna noodles, ricotta mixture, vegetables, and sauce",
      "Repeat layers, finishing with sauce and remaining cheeses on top",
      "Cover with foil and bake for 25 minutes, then uncover and bake for 15 more minutes",
      "Let stand for 10 minutes before serving, garnish with fresh basil"
    ]
  },
  {
    id: 15,
    title: "Tandoori Chicken",
    description: "Chicken marinated in yogurt and spices, traditionally cooked in a clay oven. A popular Indian dish known for its distinctive red color and smoky flavor.",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "50 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "8 chicken pieces (legs and thighs preferred)",
      "1 cup plain yogurt",
      "2 tbsp lemon juice",
      "2 tbsp ginger-garlic paste",
      "2 tbsp tandoori masala",
      "1 tsp red chili powder",
      "1 tsp garam masala",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp turmeric powder",
      "1 tsp kasuri methi (dried fenugreek leaves)",
      "2 tbsp mustard oil or vegetable oil",
      "Salt to taste",
      "Lemon wedges and sliced onions for serving"
    ],
    instructions: [
      "Make cuts in chicken pieces to allow marinade to penetrate",
      "In a bowl, mix yogurt, lemon juice, ginger-garlic paste, and all spices",
      "Add salt and oil to the marinade and mix well",
      "Refrigerate marinated chicken for at least 4 hours, preferably overnight",
      "Preheat oven to 450°F (230°C)",
      "Place chicken on a rack over a baking tray",
      "Bake for 30 minutes, turning halfway through",
      "For more color, broil for the last 5 minutes",
      "Serve hot with lemon wedges, sliced onions, and mint chutney"
    ]
  },
  {
    id: 16,
    title: "Thai Green Curry with Chicken",
    description: "Aromatic and spicy Thai curry with tender chicken, vegetables, and coconut milk. A vibrant dish bursting with authentic Thai flavors.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "35 min",
    servings: 4,
    category: "Asian",
    ingredients: [
      "500g boneless chicken thighs, cut into pieces",
      "1 can (400ml) coconut milk",
      "3 tbsp green curry paste",
      "1 cup chicken broth",
      "1 zucchini, sliced",
      "1 red bell pepper, sliced",
      "1 cup bamboo shoots, drained",
      "1 cup snap peas",
      "1 tbsp fish sauce",
      "1 tbsp palm sugar or brown sugar",
      "3-4 kaffir lime leaves",
      "1 stalk lemongrass, bruised",
      "1 tbsp vegetable oil",
      "1 handful Thai basil leaves",
      "1 red chili, sliced (optional)",
      "Lime wedges for serving"
    ],
    instructions: [
      "Heat oil in a large pot over medium heat",
      "Add green curry paste and cook for 1 minute until fragrant",
      "Add chicken pieces and cook until no longer pink on the outside",
      "Pour in coconut milk and chicken broth, bring to a simmer",
      "Add lemongrass and kaffir lime leaves",
      "Simmer for 10 minutes until chicken is cooked through",
      "Add vegetables and cook for 3-5 minutes until tender but still crisp",
      "Season with fish sauce and sugar, adjust to taste",
      "Remove from heat and stir in Thai basil leaves",
      "Serve hot over steamed rice, garnished with sliced chili and lime wedges"
    ]
  },
  {
    id: 17,
    title: "Tiramisu",
    description: "Classic Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cream. A sophisticated no-bake treat that's perfect for any occasion.",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "4 hours",
    servings: 8,
    category: "Desserts",
    ingredients: [
      "3 cups (700g) mascarpone cheese",
      "1 1/2 cups heavy cream",
      "1/3 cup granulated sugar",
      "4 large egg yolks",
      "2 tbsp amaretto or rum (optional)",
      "24-30 ladyfinger cookies",
      "1 1/2 cups strong coffee or espresso, cooled",
      "2 tbsp cocoa powder for dusting",
      "1 oz dark chocolate, grated for garnish",
      "Pinch of salt"
    ],
    instructions: [
      "In a large bowl, beat egg yolks and sugar until pale and creamy",
      "Add mascarpone cheese and beat until smooth",
      "In a separate bowl,
