
export const MOCK_RECIPES = [
  {
    id: 1,
    title: "Classic Margherita Pizza",
    description: "A traditional Italian pizza with fresh basil, mozzarella, and tomatoes. This authentic recipe brings the taste of Naples to your home kitchen.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "30 min",
    servings: 4,
    category: "Italian",
    ingredients: [
      "2 cups all-purpose flour",
      "1 cup warm water",
      "2 1/4 tsp active dry yeast",
      "Fresh mozzarella",
      "Fresh basil leaves",
      "San Marzano tomatoes",
      "Extra virgin olive oil",
      "Salt to taste"
    ],
    instructions: [
      "Prepare the pizza dough by mixing flour, yeast, and warm water",
      "Let the dough rise for 1-2 hours",
      "Stretch the dough into a circle",
      "Add tomato sauce, fresh mozzarella, and basil",
      "Bake at 450°F for 12-15 minutes"
    ]
  },
  {
    id: 2,
    title: "Chocolate Chip Cookies",
    description: "Soft and chewy cookies loaded with chocolate chips. Perfect for dessert, snack time, or special occasions.",
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "25 min",
    servings: 24,
    category: "Desserts",
    ingredients: [
      "2 1/4 cups all-purpose flour",
      "1 cup butter, softened",
      "3/4 cup white sugar",
      "3/4 cup packed brown sugar",
      "2 large eggs",
      "2 tsp vanilla extract",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "2 cups chocolate chips"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C)",
      "Cream together butter and sugars until smooth",
      "Beat in eggs one at a time, then add vanilla",
      "Combine flour, baking soda, and salt; gradually add to the wet mixture",
      "Fold in chocolate chips",
      "Drop by rounded tablespoons onto ungreased baking sheets",
      "Bake for 9 to 11 minutes or until golden brown"
    ]
  },
  {
    id: 3,
    title: "Greek Salad",
    description: "Fresh Mediterranean salad with feta cheese and olives. A healthy and refreshing side dish or light meal.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "15 min",
    servings: 2,
    category: "Salads",
    ingredients: [
      "1 large cucumber, diced",
      "2 large tomatoes, diced",
      "1 red onion, thinly sliced",
      "1 bell pepper, diced",
      "1/2 cup kalamata olives",
      "200g feta cheese, cubed",
      "2 tbsp extra virgin olive oil",
      "1 tbsp red wine vinegar",
      "1 tsp dried oregano",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Combine cucumber, tomatoes, onion, bell pepper, and olives in a large bowl",
      "Add feta cheese cubes on top",
      "In a small bowl, whisk together olive oil, vinegar, oregano, salt, and pepper",
      "Drizzle dressing over the salad and toss gently",
      "Serve immediately or refrigerate for 30 minutes to enhance flavors"
    ]
  },
  {
    id: 4,
    title: "Beef Stir Fry",
    description: "Quick and easy Asian-style beef with vegetables. A flavorful dinner ready in minutes.",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "20 min",
    servings: 4,
    category: "Asian",
    ingredients: [
      "500g beef sirloin, thinly sliced",
      "2 tbsp vegetable oil",
      "1 onion, sliced",
      "2 bell peppers, sliced",
      "2 carrots, julienned",
      "2 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "3 tbsp soy sauce",
      "1 tbsp oyster sauce",
      "1 tbsp sesame oil",
      "2 green onions, sliced for garnish",
      "Sesame seeds for garnish"
    ],
    instructions: [
      "Heat oil in a wok or large frying pan over high heat",
      "Add beef and stir-fry for 2-3 minutes until browned",
      "Remove beef and set aside",
      "In the same pan, add onion, bell peppers, and carrots. Stir-fry for 3 minutes",
      "Add garlic and ginger, stir-fry for 1 minute until fragrant",
      "Return beef to the pan, add soy sauce and oyster sauce",
      "Stir-fry everything together for 2 minutes",
      "Drizzle with sesame oil, garnish with green onions and sesame seeds"
    ]
  },
  {
    id: 5,
    title: "Banana Bread",
    description: "Moist and delicious homemade banana bread. The perfect way to use overripe bananas.",
    image: "https://images.unsplash.com/photo-1584736286279-4a5f6e2b0858?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "1 hour",
    servings: 8,
    category: "Baking",
    ingredients: [
      "3 ripe bananas, mashed",
      "1/3 cup melted butter",
      "1 tsp baking soda",
      "Pinch of salt",
      "3/4 cup sugar",
      "1 large egg, beaten",
      "1 tsp vanilla extract",
      "1 1/2 cups all-purpose flour",
      "1/2 cup walnuts or chocolate chips (optional)"
    ],
    instructions: [
      "Preheat oven to 350°F (175°C) and grease a 4x8-inch loaf pan",
      "Mix mashed bananas with melted butter in a large bowl",
      "Mix in baking soda and salt",
      "Stir in sugar, beaten egg, and vanilla extract",
      "Mix in flour",
      "Fold in nuts or chocolate chips if using",
      "Pour batter into prepared loaf pan",
      "Bake for 50-60 minutes until a toothpick inserted comes out clean"
    ]
  },
  {
    id: 6,
    title: "Vegetable Curry",
    description: "Aromatic Indian curry with mixed vegetables. A hearty vegetarian dish full of flavor.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "45 min",
    servings: 6,
    category: "Indian",
    ingredients: [
      "2 tbsp vegetable oil",
      "1 large onion, diced",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 tbsp curry powder",
      "1 tsp turmeric",
      "1 tsp ground cumin",
      "1/2 tsp red chili powder",
      "2 potatoes, diced",
      "2 carrots, sliced",
      "1 bell pepper, diced",
      "1 cup cauliflower florets",
      "1 cup green peas",
      "1 can (400ml) coconut milk",
      "1 can (400g) diced tomatoes",
      "Fresh cilantro for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Heat oil in a large pot over medium heat",
      "Add onion and sauté until translucent",
      "Add garlic and ginger, cook for 1 minute until fragrant",
      "Add curry powder, turmeric, cumin, and chili powder. Stir for 30 seconds",
      "Add potatoes, carrots, bell pepper, and cauliflower. Stir to coat with spices",
      "Add diced tomatoes and coconut milk. Bring to a simmer",
      "Cover and cook for 20 minutes until vegetables are tender",
      "Add green peas and cook for another 5 minutes",
      "Season with salt to taste and garnish with fresh cilantro"
    ]
  },
  {
    id: 7,
    title: "Butter Chicken",
    description: "Creamy and rich Indian curry with tender chicken pieces in a tomato-based sauce. A restaurant-style dish made at home.",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "45 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "500g boneless chicken thighs, cut into bite-sized pieces",
      "2 tbsp plain yogurt",
      "1 tbsp lemon juice",
      "1 tsp turmeric",
      "2 tsp garam masala",
      "1 tsp cumin",
      "2 tbsp butter",
      "1 large onion, finely chopped",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "1 can (400g) tomato puree",
      "1 cup heavy cream",
      "1 tbsp kasuri methi (dried fenugreek leaves)",
      "Fresh cilantro for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Marinate chicken with yogurt, lemon juice, turmeric, 1 tsp garam masala, and salt for at least 30 minutes",
      "Heat butter in a large pan over medium heat",
      "Add onion and sauté until golden brown",
      "Add garlic and ginger, cook for 1 minute until fragrant",
      "Add marinated chicken and cook until no longer pink, about 5-7 minutes",
      "Add tomato puree and bring to a simmer. Cook for 10 minutes",
      "Stir in heavy cream and remaining garam masala",
      "Simmer for 10 more minutes until sauce thickens",
      "Crush kasuri methi between your palms and add to the curry",
      "Adjust salt to taste and garnish with fresh cilantro"
    ]
  },
  {
    id: 8,
    title: "Palak Paneer",
    description: "Cottage cheese cubes in a creamy spinach gravy. A nutritious and popular North Indian dish.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "40 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "250g paneer, cubed",
      "500g spinach, washed",
      "2 tbsp ghee or oil",
      "1 large onion, finely chopped",
      "2 tomatoes, chopped",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 green chilies, chopped",
      "1 tsp cumin seeds",
      "1/2 tsp turmeric",
      "1 tsp garam masala",
      "1/2 tsp red chili powder",
      "2 tbsp heavy cream",
      "Salt to taste"
    ],
    instructions: [
      "Blanch spinach in boiling water for 2-3 minutes, then transfer to ice water",
      "Drain and blend the spinach into a smooth puree",
      "Heat 1 tbsp ghee in a pan and lightly fry paneer cubes until golden. Set aside",
      "In the same pan, add remaining ghee and cumin seeds",
      "When seeds splutter, add onion and sauté until golden brown",
      "Add garlic, ginger, and green chilies. Cook for 1 minute",
      "Add tomatoes and cook until soft and oil separates",
      "Add turmeric, red chili powder, and salt. Mix well",
      "Add spinach puree and cook for 5 minutes",
      "Add paneer cubes and garam masala. Simmer for 5 minutes",
      "Stir in cream and cook for 2 more minutes",
      "Serve hot with roti or rice"
    ]
  },
  {
    id: 9,
    title: "Biryani",
    description: "Aromatic rice dish with spices and tender meat. A festive and flavorful one-pot meal.",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "1 hour",
    servings: 6,
    category: "Indian",
    ingredients: [
      "500g basmati rice, soaked for 30 minutes",
      "500g chicken or lamb, cut into pieces",
      "2 large onions, thinly sliced",
      "3 tomatoes, chopped",
      "1/4 cup plain yogurt",
      "4 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 green chilies, slit",
      "1/4 cup mint leaves, chopped",
      "1/4 cup cilantro, chopped",
      "2 bay leaves",
      "4 cardamom pods",
      "1 cinnamon stick",
      "4 cloves",
      "1 star anise",
      "1 tsp cumin seeds",
      "2 tbsp biryani masala",
      "1/2 tsp turmeric",
      "1 pinch saffron soaked in 2 tbsp warm milk",
      "3 tbsp ghee or oil",
      "Salt to taste"
    ],
    instructions: [
      "Marinate meat with yogurt, half of the garlic and ginger, 1 tbsp biryani masala, turmeric, and salt for at least 1 hour",
      "Heat ghee in a large pot, add whole spices (bay leaves, cardamom, cinnamon, cloves, star anise, cumin seeds)",
      "Add sliced onions and fry until golden brown",
      "Add remaining ginger and garlic, green chilies, and sauté for 1 minute",
      "Add marinated meat and cook until browned",
      "Add tomatoes and cook until soft",
      "Add remaining biryani masala, half of the mint and cilantro. Mix well",
      "In a separate pot, cook soaked rice with salt until 70% done. Drain",
      "Layer the partially cooked rice over the meat mixture",
      "Sprinkle saffron milk and remaining mint and cilantro",
      "Cover with tight-fitting lid and cook on low heat for 20 minutes",
      "Let it rest for 5 minutes before gently mixing and serving"
    ]
  },
  {
    id: 10,
    title: "Dal Makhani",
    description: "Creamy black lentils simmered overnight. A rich and hearty vegetarian dish from Punjab.",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "45 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "1 cup whole black lentils (urad dal), soaked overnight",
      "1/4 cup red kidney beans (rajma), soaked overnight",
      "2 tbsp butter",
      "1 tbsp oil",
      "1 large onion, finely chopped",
      "2 tomatoes, pureed",
      "1 tbsp ginger-garlic paste",
      "1 green chili, slit",
      "1 tsp cumin seeds",
      "1/2 tsp turmeric",
      "1 tsp red chili powder",
      "1 tsp garam masala",
      "1/4 cup cream",
      "2 tbsp dried fenugreek leaves (kasuri methi)",
      "Fresh cilantro for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Cook soaked lentils and kidney beans with salt and turmeric in a pressure cooker until soft",
      "Heat butter and oil in a pan, add cumin seeds and let them splutter",
      "Add onion and sauté until golden brown",
      "Add ginger-garlic paste and green chili. Cook for 1 minute",
      "Add tomato puree and cook until oil separates",
      "Add red chili powder and salt. Mix well",
      "Add cooked lentils and kidney beans with their liquid",
      "Simmer on low heat for 20-25 minutes, stirring occasionally",
      "Add garam masala and dried fenugreek leaves",
      "Add cream and simmer for 5 more minutes",
      "Garnish with fresh cilantro and serve hot with naan or rice"
    ]
  },
  {
    id: 11,
    title: "Chole Bhature",
    description: "Spiced chickpeas served with fried bread. A popular Punjabi breakfast or lunch dish.",
    image: "https://images.unsplash.com/photo-1626132647957-5659d0bc9222?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "50 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "For Chole:",
      "2 cups chickpeas, soaked overnight",
      "2 large onions, finely chopped",
      "2 tomatoes, pureed",
      "1 tbsp ginger-garlic paste",
      "2 green chilies, chopped",
      "2 bay leaves",
      "1 cinnamon stick",
      "2 tsp chole masala",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp turmeric",
      "1 tsp red chili powder",
      "1 tsp amchur (dried mango powder)",
      "1 tsp garam masala",
      "2 tbsp oil",
      "Fresh cilantro for garnish",
      "For Bhature:",
      "2 cups all-purpose flour",
      "1/4 cup semolina (sooji)",
      "2 tbsp plain yogurt",
      "1/2 tsp baking powder",
      "1/4 tsp baking soda",
      "1 tbsp oil plus more for frying",
      "Warm water as needed",
      "Salt to taste"
    ],
    instructions: [
      "For Chole:",
      "Pressure cook soaked chickpeas with salt until soft",
      "Heat oil in a pan, add bay leaves and cinnamon stick",
      "Add onions and sauté until golden brown",
      "Add ginger-garlic paste and green chilies. Cook for 1 minute",
      "Add tomato puree and cook until oil separates",
      "Add all spice powders and mix well",
      "Add cooked chickpeas with some cooking liquid",
      "Simmer for 15-20 minutes until gravy thickens",
      "Garnish with fresh cilantro",
      "For Bhature:",
      "Mix flour, semolina, yogurt, baking powder, baking soda, oil, and salt",
      "Knead into a soft dough using warm water as needed",
      "Cover and let it rest for 2-3 hours",
      "Divide dough into small balls and roll into oval shapes",
      "Deep fry in hot oil until puffed and golden brown on both sides",
      "Serve hot bhature with chole"
    ]
  },
  {
    id: 50,
    title: "Masala Dosa",
    description: "Crispy rice crepe filled with spiced potatoes. A South Indian breakfast favorite.",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "30 min",
    servings: 2,
    category: "Indian",
    ingredients: [
      "For Dosa batter:",
      "2 cups rice, soaked for 4-6 hours",
      "1/2 cup urad dal, soaked for 4-6 hours",
      "1/4 tsp fenugreek seeds, soaked with urad dal",
      "Salt to taste",
      "For Potato filling:",
      "4 medium potatoes, boiled and mashed",
      "1 large onion, finely chopped",
      "1 tsp mustard seeds",
      "1 tsp cumin seeds",
      "1/4 tsp asafoetida (hing)",
      "10-15 curry leaves",
      "2-3 green chilies, finely chopped",
      "1/2 tsp turmeric powder",
      "1 tbsp oil",
      "Fresh cilantro, chopped",
      "Salt to taste",
      "For serving:",
      "Coconut chutney",
      "Sambar"
    ],
    instructions: [
      "For Dosa batter:",
      "Grind soaked rice and urad dal separately into a smooth paste",
      "Mix both pastes together, add salt, and ferment overnight",
      "For Potato filling:",
      "Heat oil in a pan, add mustard seeds and let them splutter",
      "Add cumin seeds, asafoetida, curry leaves, and green chilies",
      "Add onions and sauté until translucent",
      "Add turmeric powder and salt",
      "Add mashed potatoes and mix well. Cook for 3-4 minutes",
      "Add chopped cilantro and mix",
      "To make Masala Dosa:",
      "Heat a non-stick griddle or tawa",
      "Pour a ladleful of batter and spread in a circular motion",
      "Drizzle oil around the edges and cook until golden and crisp",
      "Place a portion of potato filling in the center",
      "Fold the dosa over the filling and serve hot with coconut chutney and sambar"
    ]
  },
  {
    id: 12,
    title: "Paneer Tikka Masala",
    description: "Grilled paneer cubes in a rich and creamy tomato-based sauce. A vegetarian delight that's popular in Indian restaurants worldwide.",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "40 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "400g paneer, cut into cubes",
      "1 large onion, finely chopped",
      "2 tomatoes, pureed",
      "3 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 green chilies, slit",
      "1 tbsp tandoori masala",
      "1 tsp garam masala",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp turmeric powder",
      "1 tsp kasuri methi (dried fenugreek leaves)",
      "200ml heavy cream",
      "2 tbsp vegetable oil",
      "2 tbsp butter",
      "Fresh cilantro for garnish",
      "Salt to taste"
    ],
    instructions: [
      "Marinate paneer cubes in yogurt, tandoori masala, and salt for 30 minutes",
      "Grill or pan-fry the marinated paneer until golden and set aside",
      "Heat oil and butter in a pan, add cumin seeds and let them splutter",
      "Add onions and sauté until golden brown",
      "Add ginger, garlic, and green chilies, cook for 1-2 minutes",
      "Add tomato puree and cook until oil separates",
      "Add all the spice powders and mix well",
      "Add cream and simmer for 5 minutes",
      "Add the grilled paneer and kasuri methi, simmer for another 5 minutes",
      "Garnish with fresh cilantro and serve hot with naan or rice"
    ]
  },
  {
    id: 13,
    title: "Mushroom Risotto",
    description: "Creamy Italian rice dish with mushrooms and Parmesan cheese. A comforting vegetarian meal that's both elegant and satisfying.",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "35 min",
    servings: 4,
    category: "Italian",
    ingredients: [
      "1 1/2 cups Arborio rice",
      "300g mixed mushrooms (cremini, shiitake, oyster), sliced",
      "1 medium onion, finely diced",
      "2 cloves garlic, minced",
      "1/2 cup dry white wine",
      "4 cups vegetable broth, kept warm",
      "1/2 cup grated Parmesan cheese",
      "2 tbsp butter",
      "2 tbsp olive oil",
      "2 tbsp fresh thyme leaves",
      "1 tbsp fresh parsley, chopped",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Heat olive oil in a large pan, add mushrooms and cook until golden brown",
      "Remove mushrooms and set aside",
      "In the same pan, add butter, onion, and garlic. Sauté until translucent",
      "Add Arborio rice and toast for 2-3 minutes",
      "Pour in white wine and stir until absorbed",
      "Gradually add warm broth, one ladle at a time, stirring constantly",
      "Continue adding broth and stirring until rice is creamy and al dente (about 18-20 minutes)",
      "Stir in cooked mushrooms, Parmesan cheese, and thyme",
      "Season with salt and pepper, garnish with parsley",
      "Serve immediately for the best creamy texture"
    ]
  },
  {
    id: 14,
    title: "Vegetable Lasagna",
    description: "Layers of pasta, rich tomato sauce, and assorted vegetables topped with creamy béchamel and cheese. A hearty vegetarian twist on the Italian classic.",
    image: "https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "75 min",
    servings: 8,
    category: "Italian",
    ingredients: [
      "12 lasagna noodles",
      "2 zucchini, diced",
      "1 eggplant, diced",
      "1 red bell pepper, diced",
      "2 cups spinach, chopped",
      "1 large onion, diced",
      "3 cloves garlic, minced",
      "2 cans (400g each) crushed tomatoes",
      "2 tbsp tomato paste",
      "1 tsp dried oregano",
      "1 tsp dried basil",
      "1/4 tsp red pepper flakes",
      "2 cups ricotta cheese",
      "2 cups mozzarella cheese, shredded",
      "1 cup Parmesan cheese, grated",
      "1 egg, beaten",
      "3 tbsp olive oil",
      "Salt and pepper to taste",
      "Fresh basil for garnish"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C)",
      "Cook lasagna noodles according to package instructions",
      "In a large pan, heat olive oil and sauté onions and garlic until soft",
      "Add zucchini, eggplant, and bell pepper. Cook until tender",
      "Add crushed tomatoes, tomato paste, dried herbs, and seasonings",
      "Simmer sauce for 15-20 minutes until slightly thickened",
      "In a bowl, mix ricotta cheese, half the mozzarella, half the Parmesan, and the beaten egg",
      "In a 9x13 baking dish, spread a thin layer of tomato sauce",
      "Layer with lasagna noodles, ricotta mixture, vegetables, and sauce",
      "Repeat layers, finishing with sauce and remaining cheeses on top",
      "Cover with foil and bake for 25 minutes, then uncover and bake for 15 more minutes",
      "Let stand for 10 minutes before serving, garnish with fresh basil"
    ]
  },
  {
    id: 15,
    title: "Tandoori Chicken",
    description: "Chicken marinated in yogurt and spices, traditionally cooked in a clay oven. A popular Indian dish known for its distinctive red color and smoky flavor.",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "50 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "8 chicken pieces (legs and thighs preferred)",
      "1 cup plain yogurt",
      "2 tbsp lemon juice",
      "2 tbsp ginger-garlic paste",
      "2 tbsp tandoori masala",
      "1 tsp red chili powder",
      "1 tsp garam masala",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp turmeric powder",
      "1 tsp kasuri methi (dried fenugreek leaves)",
      "2 tbsp mustard oil or vegetable oil",
      "Salt to taste",
      "Lemon wedges and sliced onions for serving"
    ],
    instructions: [
      "Make cuts in chicken pieces to allow marinade to penetrate",
      "In a bowl, mix yogurt, lemon juice, ginger-garlic paste, and all spices",
      "Add salt and oil to the marinade and mix well",
      "Refrigerate marinated chicken for at least 4 hours, preferably overnight",
      "Preheat oven to 450°F (230°C)",
      "Place chicken on a rack over a baking tray",
      "Bake for 30 minutes, turning halfway through",
      "For more color, broil for the last 5 minutes",
      "Serve hot with lemon wedges, sliced onions, and mint chutney"
    ]
  },
  {
    id: 16,
    title: "Thai Green Curry with Chicken",
    description: "Aromatic and spicy Thai curry with tender chicken, vegetables, and coconut milk. A vibrant dish bursting with authentic Thai flavors.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "35 min",
    servings: 4,
    category: "Asian",
    ingredients: [
      "500g boneless chicken thighs, cut into pieces",
      "1 can (400ml) coconut milk",
      "3 tbsp green curry paste",
      "1 cup chicken broth",
      "1 zucchini, sliced",
      "1 red bell pepper, sliced",
      "1 cup bamboo shoots, drained",
      "1 cup snap peas",
      "1 tbsp fish sauce",
      "1 tbsp palm sugar or brown sugar",
      "3-4 kaffir lime leaves",
      "1 stalk lemongrass, bruised",
      "1 tbsp vegetable oil",
      "1 handful Thai basil leaves",
      "1 red chili, sliced (optional)",
      "Lime wedges for serving"
    ],
    instructions: [
      "Heat oil in a large pot over medium heat",
      "Add green curry paste and cook for 1 minute until fragrant",
      "Add chicken pieces and cook until no longer pink on the outside",
      "Pour in coconut milk and chicken broth, bring to a simmer",
      "Add lemongrass and kaffir lime leaves",
      "Simmer for 10 minutes until chicken is cooked through",
      "Add vegetables and cook for 3-5 minutes until tender but still crisp",
      "Season with fish sauce and sugar, adjust to taste",
      "Remove from heat and stir in Thai basil leaves",
      "Serve hot over steamed rice, garnished with sliced chili and lime wedges"
    ]
  },
  {
    id: 17,
    title: "Tiramisu",
    description: "Classic Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cream. A sophisticated no-bake treat that's perfect for any occasion.",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "4 hours",
    servings: 8,
    category: "Desserts",
    ingredients: [
      "3 cups (700g) mascarpone cheese",
      "1 1/2 cups heavy cream",
      "1/3 cup granulated sugar",
      "4 large egg yolks",
      "2 tbsp amaretto or rum (optional)",
      "24-30 ladyfinger cookies",
      "1 1/2 cups strong coffee or espresso, cooled",
      "2 tbsp cocoa powder for dusting",
      "1 oz dark chocolate, grated for garnish",
      "Pinch of salt"
    ],
    instructions: [
      "In a large bowl, beat egg yolks and sugar until pale and creamy",
      "Add mascarpone cheese and beat until smooth",
      "In a separate bowl, whip heavy cream until stiff peaks form",
      "Gently fold whipped cream into mascarpone mixture",
      "Dip ladyfingers quickly in coffee and arrange in a single layer in a dish",
      "Spread half of the mascarpone mixture over the ladyfingers",
      "Repeat with another layer of coffee-dipped ladyfingers",
      "Top with remaining mascarpone mixture and smooth the surface",
      "Dust generously with cocoa powder and refrigerate for at least 4 hours",
      "Before serving, garnish with grated chocolate"
    ]
  },
  {
    id: 18,
    title: "Spaghetti Carbonara",
    description: "Authentic Italian pasta dish with eggs, cheese, pancetta and black pepper. Simple yet delicious comfort food from Rome.",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "25 min",
    servings: 4,
    category: "Italian",
    ingredients: [
      "400g spaghetti",
      "150g pancetta or guanciale, diced",
      "4 large eggs",
      "100g Pecorino Romano, grated",
      "50g Parmigiano Reggiano, grated",
      "Freshly ground black pepper",
      "Salt to taste"
    ],
    instructions: [
      "Bring a large pot of salted water to boil and cook pasta until al dente",
      "Meanwhile, in a large pan, cook pancetta until crispy",
      "In a bowl, whisk eggs and mix in the grated cheeses",
      "When pasta is ready, reserve 1/2 cup of cooking water and drain",
      "Working quickly, add hot pasta to the pan with pancetta",
      "Remove pan from heat and quickly stir in the egg and cheese mixture",
      "Add a splash of pasta water to create a creamy sauce",
      "Season generously with freshly ground black pepper",
      "Serve immediately with extra grated cheese on top"
    ]
  },
  {
    id: 19,
    title: "Mango Sticky Rice",
    description: "Sweet Thai dessert featuring glutinous rice, fresh mango, and coconut cream. A tropical treat that's both refreshing and satisfying.",
    image: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "30 min",
    servings: 4,
    category: "Asian",
    ingredients: [
      "2 cups glutinous rice, soaked for 4 hours",
      "1 1/2 cups coconut milk",
      "3/4 cup sugar",
      "1/2 tsp salt",
      "2 ripe mangoes, peeled and sliced",
      "1 tbsp toasted sesame seeds or mung beans",
      "Fresh mint leaves for garnish"
    ],
    instructions: [
      "Steam soaked glutinous rice for 25 minutes until cooked through",
      "In a saucepan, heat 1 cup coconut milk with sugar and salt until dissolved",
      "Pour the coconut mixture over the hot rice and mix well",
      "Cover and let it sit for 30 minutes to absorb the flavors",
      "For the sauce, heat remaining coconut milk with a pinch of salt until warm",
      "To serve, place a portion of sticky rice on a plate",
      "Arrange mango slices beside the rice",
      "Drizzle with the warm coconut sauce",
      "Sprinkle with toasted sesame seeds and garnish with mint leaves"
    ]
  },
  {
    id: 20,
    title: "Fish Tacos",
    description: "Light and flavorful tacos with crispy fish, fresh cabbage slaw, and zesty sauce. A Baja California classic that's perfect for casual dining.",
    image: "https://images.unsplash.com/photo-1512838243191-e81e8f66f1fd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "30 min",
    servings: 4,
    category: "Mexican",
    ingredients: [
      "1 pound white fish fillets (cod, tilapia, or mahi-mahi)",
      "2 cups shredded cabbage",
      "1/2 cup sour cream",
      "2 tbsp lime juice",
      "1 tsp hot sauce",
      "1 cup all-purpose flour",
      "1 tsp chili powder",
      "1 tsp cumin",
      "1/2 tsp garlic powder",
      "Salt and pepper to taste",
      "Vegetable oil for frying",
      "8 corn tortillas",
      "Avocado slices, cilantro, and lime wedges for serving"
    ],
    instructions: [
      "In a bowl, mix sour cream, 1 tbsp lime juice, and hot sauce to make the sauce",
      "Toss cabbage with remaining lime juice and salt to make the slaw",
      "In a shallow dish, mix flour with chili powder, cumin, garlic powder, salt, and pepper",
      "Cut fish into strips and coat with the seasoned flour",
      "Heat oil in a large pan and fry fish until golden and crispy, about 2-3 minutes per side",
      "Warm the tortillas in a dry pan or microwave",
      "Assemble tacos with fish, cabbage slaw, sauce, avocado slices, and cilantro",
      "Serve with lime wedges on the side"
    ]
  },
  {
    id: 21,
    title: "Beef Wellington",
    description: "Elegant dish of tender beef fillet wrapped in mushroom duxelles, prosciutto, and flaky puff pastry. A showstopping centerpiece for special occasions.",
    image: "https://images.unsplash.com/photo-1624726175512-19b9baf9fbd1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "2 hours",
    servings: 6,
    category: "European",
    ingredients: [
      "1.5 kg beef tenderloin",
      "500g mushrooms, finely chopped",
      "4 shallots, minced",
      "4 cloves garlic, minced",
      "8 slices prosciutto or Parma ham",
      "2 tbsp Dijon mustard",
      "500g puff pastry",
      "2 egg yolks, beaten for egg wash",
      "2 tbsp olive oil",
      "2 tbsp fresh thyme, chopped",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Season beef with salt and pepper and sear in hot oil until browned on all sides",
      "Let the beef cool completely",
      "Cook mushrooms, shallots, garlic, and thyme until moisture evaporates",
      "Cool the mushroom mixture (duxelles)",
      "Lay out plastic wrap and arrange prosciutto slices in a rectangle",
      "Spread duxelles over the prosciutto",
      "Brush cooled beef with Dijon mustard and place on mushroom mixture",
      "Using plastic wrap, roll into a tight cylinder and chill for 30 minutes",
      "Roll out puff pastry and remove plastic from beef",
      "Place beef in the center of pastry and fold over, sealing edges with egg wash",
      "Brush entire pastry with egg wash and make small slits on top",
      "Bake at 425°F (220°C) for 40-45 minutes for medium-rare",
      "Rest for 10 minutes before slicing and serving"
    ]
  },
  {
    id: 22,
    title: "Shakshuka",
    description: "North African and Middle Eastern dish of eggs poached in a spiced tomato sauce. A versatile one-pan wonder that's perfect for breakfast, lunch, or dinner.",
    image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "30 min",
    servings: 4,
    category: "Mediterranean",
    ingredients: [
      "2 tbsp olive oil",
      "1 onion, diced",
      "1 red bell pepper, diced",
      "4 cloves garlic, minced",
      "2 tsp paprika",
      "1 tsp cumin",
      "1/4 tsp chili flakes",
      "1 can (800g) crushed tomatoes",
      "6 large eggs",
      "1/2 cup crumbled feta cheese",
      "Fresh parsley or cilantro, chopped",
      "Salt and pepper to taste",
      "Crusty bread for serving"
    ],
    instructions: [
      "Heat oil in a large skillet over medium heat",
      "Add onion and bell pepper, cook until softened",
      "Add garlic and spices, cook for 1 minute until fragrant",
      "Pour in crushed tomatoes, season with salt and pepper",
      "Simmer for 10 minutes until slightly thickened",
      "Make 6 indentations in the sauce and crack an egg into each",
      "Cover and cook for 5-8 minutes until eggs are set",
      "Sprinkle with feta cheese and herbs",
      "Serve hot with crusty bread for dipping"
    ]
  },
  {
    id: 23,
    title: "Ramen",
    description: "Japanese noodle soup with rich broth, tender meat, and various toppings. A comforting bowl that's both hearty and flavorful.",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "1.5 hours",
    servings: 4,
    category: "Asian",
    ingredients: [
      "4 packets ramen noodles (discard seasoning packets)",
      "8 cups chicken or pork broth",
      "4 chicken thighs or pork belly slices",
      "4 soft-boiled eggs, halved",
      "2 cups baby bok choy, halved",
      "4 green onions, sliced",
      "4 cloves garlic, minced",
      "1 tbsp ginger, grated",
      "2 tbsp soy sauce",
      "1 tbsp mirin",
      "1 tbsp sesame oil",
      "Nori sheets, cut into strips",
      "Bean sprouts for topping",
      "Chili oil for serving (optional)"
    ],
    instructions: [
      "In a large pot, bring broth to a simmer with garlic, ginger, soy sauce, and mirin",
      "Add meat and simmer until tender, about 30-40 minutes",
      "Remove meat, slice thinly, and set aside",
      "Blanch bok choy in the broth for 2 minutes and set aside",
      "Cook ramen noodles according to package instructions",
      "Drain noodles and divide among bowls",
      "Ladle hot broth over noodles",
      "Arrange sliced meat, bok choy, soft-boiled egg halves on top",
      "Garnish with green onions, nori strips, and bean sprouts",
      "Drizzle with sesame oil and chili oil if desired"
    ]
  },
  {
    id: 24,
    title: "Paella",
    description: "Spanish rice dish with saffron, seafood, and meat. A colorful and festive one-pan meal that's perfect for sharing.",
    image: "https://images.unsplash.com/photo-1515443961218-a51367888e4b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "1 hour",
    servings: 6,
    category: "European",
    ingredients: [
      "2 cups Spanish short-grain rice (bomba or calasparra)",
      "4 cups chicken broth",
      "1 pinch saffron threads",
      "8 large shrimp, shell-on",
      "8 mussels, cleaned",
      "8 clams, cleaned",
      "2 chicken thighs, cut into pieces",
      "100g chorizo, sliced",
      "1 onion, chopped",
      "1 red bell pepper, diced",
      "3 cloves garlic, minced",
      "1 large tomato, grated",
      "1/2 cup frozen peas",
      "1/4 cup parsley, chopped",
      "3 tbsp olive oil",
      "1 lemon, cut into wedges",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Heat broth with saffron and keep warm",
      "In a paella pan or large skillet, heat olive oil over medium-high heat",
      "Season chicken with salt and pepper and cook until browned",
      "Add chorizo and cook for 2 minutes",
      "Add onion, bell pepper, and garlic, cook until softened",
      "Stir in grated tomato and cook for 2-3 minutes",
      "Add rice and stir to coat with oil and vegetables",
      "Pour in warm broth, stir once, and reduce heat to low",
      "Simmer for 10 minutes without stirring",
      "Arrange shrimp, mussels, and clams on top, pushing slightly into the rice",
      "Scatter peas over the top and continue to cook until liquid is absorbed",
      "If the bottom is not crispy (socarrat), increase heat for 1-2 minutes",
      "Remove from heat, cover with a clean cloth, and let rest for 5 minutes",
      "Garnish with parsley and lemon wedges before serving"
    ]
  },
  {
    id: 25,
    title: "Chocolate Lava Cake",
    description: "Decadent dessert with a warm, flowing chocolate center. A chocolate lover's dream that's surprisingly easy to make.",
    image: "https://images.unsplash.com/photo-1600326145308-ea55100844a0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "25 min",
    servings: 4,
    category: "Desserts",
    ingredients: [
      "115g dark chocolate, chopped",
      "115g unsalted butter",
      "2 whole eggs",
      "2 egg yolks",
      "1/4 cup granulated sugar",
      "2 tbsp all-purpose flour",
      "1 tbsp cocoa powder, plus more for dusting",
      "Pinch of salt",
      "Vanilla ice cream for serving"
    ],
    instructions: [
      "Preheat oven to 425°F (220°C) and grease four ramekins",
      "Dust ramekins with cocoa powder",
      "Melt chocolate and butter together in a double boiler or microwave",
      "In a separate bowl, whisk eggs, egg yolks, and sugar until pale and thick",
      "Fold the chocolate mixture into the egg mixture",
      "Sift in flour, cocoa powder, and salt, and fold gently until combined",
      "Divide batter among ramekins",
      "Bake for 12-14 minutes until edges are set but centers are soft",
      "Let cool for 1 minute, then run a knife around the edges",
      "Invert onto serving plates and dust with cocoa powder",
      "Serve immediately with vanilla ice cream"
    ]
  },
  {
    id: 26,
    title: "Chicken Tikka",
    description: "Tender chunks of chicken marinated in spiced yogurt and grilled to perfection. A popular Indian appetizer that's bursting with flavor.",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "40 min",
    servings: 4,
    category: "Indian",
    ingredients: [
      "500g boneless chicken, cut into 2-inch pieces",
      "1 cup plain yogurt",
      "2 tbsp lemon juice",
      "1 tbsp ginger paste",
      "1 tbsp garlic paste",
      "2 tsp garam masala",
      "1 tsp ground cumin",
      "1 tsp ground coriander",
      "1 tsp turmeric",
      "1 tsp red chili powder",
      "1 tsp paprika for color",
      "2 tbsp oil",
      "Salt to taste",
      "Fresh cilantro and lemon wedges for garnish"
    ],
    instructions: [
      "In a large bowl, mix yogurt, lemon juice, ginger, garlic, and all spices",
      "Add chicken pieces and mix well to coat",
      "Cover and refrigerate for at least 2 hours, preferably overnight",
      "Preheat grill or oven to 425°F (220°C)",
      "Thread marinated chicken onto skewers (if using wooden skewers, soak in water first)",
      "Brush with oil and grill for 10-12 minutes, turning occasionally",
      "Alternatively, bake in oven for 15-20 minutes until cooked through",
      "Serve hot, garnished with cilantro and lemon wedges",
      "Perfect with mint chutney and naan bread"
    ]
  },
  {
    id: 27,
    title: "Pho",
    description: "Vietnamese noodle soup with aromatic broth, rice noodles, and thinly sliced beef. A comforting bowl that's full of complex flavors.",
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "3 hours",
    servings: 6,
    category: "Asian",
    ingredients: [
      "2 kg beef bones (knuckle, marrow, or shank)",
      "1 kg beef brisket or chuck, whole piece",
      "500g rice noodles",
      "200g beef sirloin, thinly sliced",
      "2 onions, halved",
      "1 piece ginger (100g), sliced",
      "5 star anise pods",
      "1 cinnamon stick",
      "3 cloves",
      "1 tbsp coriander seeds",
      "2 tbsp fish sauce",
      "1 tbsp sugar",
      "For serving: bean sprouts, Thai basil, lime wedges, sliced chilies, hoisin sauce, sriracha"
    ],
    instructions: [
      "Parboil beef bones for 5 minutes, drain and rinse thoroughly",
      "In a large pot, add bones, brisket, and 5 liters of water",
      "Bring to a boil, then reduce to a simmer",
      "Meanwhile, char onions and ginger in a dry pan or under the broiler",
      "Add charred onions, ginger, and all spices to the broth",
      "Simmer for 2-3 hours, skimming occasionally",
      "Remove brisket when tender (about 1.5 hours), let cool and slice thinly",
      "After broth is done, strain and season with fish sauce and sugar",
      "Cook rice noodles according to package instructions",
      "To serve, place noodles in bowls, top with sliced brisket and raw sirloin",
      "Pour hot broth over to cook the raw beef",
      "Serve with garnishes on the side for everyone to add as desired"
    ]
  },
  {
    id: 28,
    title: "Caesar Salad",
    description: "Classic salad with crisp romaine lettuce, parmesan cheese, croutons, and creamy dressing. A timeless appetizer or light meal.",
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
    time: "20 min",
    servings: 4,
    category: "Salads",
    ingredients: [
      "2 heads romaine lettuce, washed and torn into bite-sized pieces",
      "1 cup croutons, homemade or store-bought",
      "1/2 cup freshly grated parmesan cheese, plus more for serving",
      "For the dressing:",
      "2 cloves garlic, minced",
      "2 anchovy fillets, minced (optional)",
      "1 large egg yolk",
      "2 tbsp fresh lemon juice",
      "1 tsp Dijon mustard",
      "1/2 cup olive oil",
      "1/4 tsp Worcestershire sauce",
      "Salt and freshly ground black pepper to taste"
    ],
    instructions: [
      "For the dressing, whisk together garlic, anchovies, egg yolk, lemon juice, and mustard",
      "Slowly drizzle in olive oil while whisking continuously to emulsify",
      "Stir in Worcestershire sauce, salt, and pepper",
      "In a large bowl, toss romaine lettuce with enough dressing to coat",
      "Add croutons and grated parmesan, toss lightly",
      "Serve immediately with extra parmesan on top",
      "For added protein, top with grilled chicken or shrimp"
    ]
  }
];
